=== ouyangbuchifan/js-RuMenJingTong/14章/myDogs.dtd
<!--The myDogs DTD-->
	<!ELEMENT myDogs (dog+)>

	<!--The <dog/> section-->
		<!ELEMENT dog(name,age,fullBlood,color)>
		<!ATTLIST name(#PCDATA)>
		<!--#PCDATA表示age的子元素是有严格顺序的-->
		<!ELEMENT age(years,month)>
			<!--the <age/> section-->
			<!ELEMENT month(#PCDATA)>
			<!ELEMENT years(#PCDATA)>
			<!--END age section-->
		<!ELEMENT fullBlood (#PCDATA)>	
		<!ELEMENT color (#PCDATA)>
		<!--END <dog/> section-->
<!--END myDogs DTD-->

=== ouyangbuchifan/js-RuMenJingTong/14章/demo1.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE myDogs SYSTEM "myDogs.dtd">
<myDogs>
    <dog breed="Labrador Retriever">
        <name>Morgan</name>
        <age>
            <years>0</years>
             <month>10</month>
        </age>
        <fullBlood>yes</fullBlood>
        <color>chocolate</color>
    </dog>
    <dog breed="Labrador Retriever">
        <name>Molly</name>
        <age>
            <years>8</years>
            <month>11</month>
        </age>
        <fullBlood>yes</fullBlood>
        <color>yellow</color>
    </dog>
    <dog breed="Pomeranian">
        <name>Casey</name>
        <age>
        	<years>6</years>
        	<months>2</months>
        </age>
        <fullBlood>yes</fullBlood>
        <color>brown</color>
    </dog>
</myDogs>
